version: "3.8"
services:
    frontend:
        build:
            context: .
            args:
                REACT_APP_BACKEND_URL: ${BACKEND_URL}

        image: "magnusramm/garduino:latest"
        ports:
            - "3000:3000"
        depends_on:
            - backend
    backend:
        build: ../gardiner_backend
        image: "magnusramm/garduino_backend:latest"
        ports:
            - "8080:8080"
        